In [18]:
r = 0.05
w_hs = 40_000
c_college = 5_000
w_college = 50_000
#

In [52]:
soma = 0
soma2 = 0
soma3 = 0
for t in range(0 , 40):
    hs_npv_sum = w_hs*((1 + r)**t)
    college_npv_w = w_college*((1 + r)**t)
    soma = soma + hs_npv_sum
    soma2 = soma2 + college_npv_w
for t in range(0 , 4):
    college_npv_cost = c_college*((1 + r)**t)
    soma3 = soma3 + college_npv_cost
print(soma, "high school npv sum")
print(soma2, "college npv wage")
print(soma3, "college npv cost")
college_npv_sum = college_npv_w - college_npv_cost
print(college_npv_sum, "college npv sum")

4831990.969699722 high school npv sum
6039988.712124652 college npv wage
21550.625 college npv cost
329449.4327202218 college npv sum


In [53]:
college_npv_sum > hs_npv_sum

True

In [58]:
import numpy as np

In [59]:
x1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
x2_list = [[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
x2 = np.array(x2_list)
print(x2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [66]:
print(x2[1, 1, 2])

60


In [68]:
print(x2[[(0, 1, 1), (0, 1, 1)], [(1, 1, 1), (1, 1, 1)]])

[[[ 4  5  6]
  [40 50 60]
  [40 50 60]]

 [[ 4  5  6]
  [40 50 60]
  [40 50 60]]]


In [96]:
print(np.array((x2[0, 1, 1:3], x2[1, 1, 1:3])))

[[ 5  6]
 [50 60]]


In [102]:
sizes = (2, 4, 4)
x = np.zeros(sizes)
y = np.ones(sizes)
print(1+x)
print(2*y)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [106]:
3*x2_list

[[[1, 2, 3], [4, 5, 6]],
 [[10, 20, 30], [40, 50, 60]],
 [[1, 2, 3], [4, 5, 6]],
 [[10, 20, 30], [40, 50, 60]],
 [[1, 2, 3], [4, 5, 6]],
 [[10, 20, 30], [40, 50, 60]]]